<?php
/* --------------------------------------------------
   AJAX HANDLER: MUST RUN BEFORE ANY HTML OUTPUT OR HEADERS
-------------------------------------------------- */
if (isset($_GET['action']) && $_GET['action'] === 'get_order_details') {
    ini_set('display_errors', 0);
    header('Content-Type: application/json');
    
    try {
        // 1. Start output buffering to capture HTML markup generated by header.php
        ob_start();
        
        // 2. Include the header to leverage its session protection rules and $pdo initialization
        require_once __DIR__ . '/inc/header.php';
        
        // 3. Immediately purge the generated header HTML so it doesn't corrupt our strict JSON channel
        ob_clean(); 

        $order_string = trim($_GET['order_ids'] ?? '');
        $target_user_id = (int)($_GET['user_id'] ?? 0);
        
        if (empty($order_string)) {
            echo json_encode(['success' => false, 'error' => 'No order IDs supplied']);
            exit;
        }

        // Clean and explode values like "2,3" safely
        $order_ids = array_filter(array_map('intval', explode(',', $order_string)));

        if (empty($order_ids)) {
            echo json_encode(['success' => false, 'error' => 'Invalid order structure']);
            exit;
        }

        // Fetch corresponding User data directly matching the specified criteria
        $user_stmt = $pdo->prepare("SELECT full_name, email, country FROM users WHERE id = ?");
        $user_stmt->execute([$target_user_id]);
        $user_data = $user_stmt->fetch(PDO::FETCH_ASSOC);
        
        if (!$user_data) {
            $user_data = [
                'full_name' => 'Unknown User', 
                'email' => 'N/A', 
                'country' => 'N/A'
            ];
        }

        // Prepare dynamic in-clause placeholder string for processing ticket parameters
        $placeholders = implode(',', array_fill(0, count($order_ids), '?'));
        
        // CORRECTED INTERMEDIARY LAYER JOIN ROUTE
        $stmt = $pdo->prepare("
            SELECT 
                t.ticket_id, t.ticket_name, t.section_name, t.row_name, t.price,
                c.concert_id, c.concert_date, c.day_time, c.venue, c.location, c.title AS concert_title,
                a.artist_id, a.artist_name, a.artist_image,
                o.order_id
            FROM orders o
            INNER JOIN tickets t ON o.ticket_id = t.ticket_id
            LEFT JOIN concerts c ON t.concert_id = c.concert_id
            LEFT JOIN artists a ON c.artist_id = a.artist_id
            WHERE o.order_id IN ($placeholders)
        ");
        $stmt->execute($order_ids);
        $tickets_data = $stmt->fetchAll(PDO::FETCH_ASSOC);

        echo json_encode([
            'success' => true,
            'user' => $user_data,
            'items' => $tickets_data
        ]);
    } catch (Exception $e) {
        echo json_encode(['success' => false, 'error' => $e->getMessage()]);
    }
    exit;
}

/* --------------------------------------------------
   GLOBAL COMPONENT CONFIGURATION: STANDARD ROUTE VIEW
-------------------------------------------------- */
ini_set('display_errors', 1);
error_reporting(E_ALL);

require_once __DIR__ . '/inc/header.php';

$message = '';
$error   = '';

/* --------------------------------------------------
   FETCH ALL DEPOSITS WITH USER & METHOD DETAILS
-------------------------------------------------- */
try {
    $stmt = $pdo->query("
        SELECT 
            d.*, 
            u.id as user_uid, 
            u.country,
            pm.image_path as method_logo
        FROM deposits d
        LEFT JOIN users u ON d.user_id = u.id
        LEFT JOIN payment_methods pm ON d.payment_id = pm.payment_id
        ORDER BY d.deposit_id DESC
    ");
    $deposits = $stmt->fetchAll(PDO::FETCH_ASSOC);
} catch (PDOException $e) {
    $error = "Database error: " . $e->getMessage();
    $deposits = [];
}

/* --------------------------------------------------
   HANDLE ACTIONS
-------------------------------------------------- */
if ($_SERVER['REQUEST_METHOD'] === 'POST' && !$error) {

    $action = $_POST['action'] ?? '';

    try {

        /* ---------------- UPDATE STATUS (APPROVE/DECLINE) ---------------- */
/* ---------------- UPDATE STATUS (APPROVE/DECLINE) ---------------- */
        if ($action === 'update_status') {
            $id = (int)($_POST['id'] ?? 0);
            $new_status = $_POST['status'] ?? '';

            if ($id <= 0 || !in_array($new_status, ['approved', 'declined', 'pending'])) {
                throw new Exception("Invalid parameters provided.");
            }

            // Begin Transaction to guarantee data integrity across both logs
            $pdo->beginTransaction();

            // 1. Fetch current deposit to check if it's an order payment or wallet top-up, plus amount and user_id
            $check_stmt = $pdo->prepare("SELECT user_id, amount, order_ids, status FROM deposits WHERE deposit_id = ?");
            $check_stmt->execute([$id]);
            $deposit_record = $check_stmt->fetch(PDO::FETCH_ASSOC);

            if (!$deposit_record) {
                throw new Exception("Target deposit record not found.");
            }

            // Prevent double-crediting if an admin accidentally double-clicks or re-approves an already approved deposit
            if ($new_status === 'approved' && $deposit_record['status'] === 'approved') {
                throw new Exception("This deposit has already been approved and credited.");
            }

            // 2. Update status column on the individual deposit record
            $stmt = $pdo->prepare("UPDATE deposits SET status = ? WHERE deposit_id = ?");
            $stmt->execute([$new_status, $id]);

            // 3. Handle processing on 'approved' actions
            if ($new_status === 'approved') {
                $order_string = trim($deposit_record['order_ids'] ?? '');
                $is_order_payment = (!empty($order_string) && $order_string !== '0');

                if ($is_order_payment) {
                    // --- CASE A: Route for Order Ticket Completions ---
                    $order_ids = array_filter(array_map('intval', explode(',', $order_string)));
                    
                    if (!empty($order_ids)) {
                        $placeholders = implode(',', array_fill(0, count($order_ids), '?'));
                        $order_stmt = $pdo->prepare("UPDATE orders SET status = 'completed' WHERE order_id IN ($placeholders)");
                        $order_stmt->execute($order_ids);
                    }
                } else {
                    // --- CASE B: Route for Direct Balance Top-up ---
                    $target_user = (int)$deposit_record['user_id'];
                    $topup_amount = (float)$deposit_record['amount'];

                    if ($target_user > 0 && $topup_amount > 0) {
                        // Adjust table and column names (`balance`, `wallet_balance`, etc.) to match your exact DB architecture
                        $user_balance_stmt = $pdo->prepare("UPDATE users SET balance = balance + ? WHERE id = ?");
                        $user_balance_stmt->execute([$topup_amount, $target_user]);
                    } else {
                        throw new Exception("Invalid user or amount allocation parameters for wallet top-up.");
                    }
                }
            }

            $pdo->commit();

            $_SESSION['success'] = "Deposit payment reference status changed to " . ucfirst($new_status) . ".";
            header("Location: " . $_SERVER['PHP_SELF']);
            exit;
        }

        /* ---------------- DELETE DEPOSIT RECORD ---------------- */
        if ($action === 'delete') {

            $id = (int)($_POST['id'] ?? 0);

            if ($id <= 0) {
                throw new Exception("Invalid deposit entry ID.");
            }

            $stmt = $pdo->prepare("DELETE FROM deposits WHERE deposit_id = ?");
            $stmt->execute([$id]);

            $_SESSION['success'] = "Deposit reference history log deleted successfully.";
            header("Location: " . $_SERVER['PHP_SELF']);
            exit;
        }

    } catch (Exception $e) {
        if ($pdo->inTransaction()) {
            $pdo->rollBack();
        }
        $_SESSION['error'] = $e->getMessage();
        header("Location: " . $_SERVER['PHP_SELF']);
        exit;
    }
}
?>

<main>

<h1 style="text-align:center; margin:2rem 0;">Manage Client Deposits</h1>

<?php if (!empty($_SESSION['success'])): ?>
<div style="background:#238636;color:#fff;padding:1rem;border-radius:8px;text-align:center;max-width:1100px;margin:1rem auto;">
    <?= htmlspecialchars($_SESSION['success']) ?>
</div>
<?php unset($_SESSION['success']); ?>
<?php endif; ?>

<?php if (!empty($_SESSION['error'])): ?>
<div style="background:#f85149;color:#fff;padding:1rem;border-radius:8px;text-align:center;max-width:1100px;margin:1rem auto;">
    <?= htmlspecialchars($_SESSION['error']) ?>
</div>
<?php unset($_SESSION['error']); ?>
<?php endif; ?>

<div style="max-width:1100px;margin:0 auto 1.5rem auto;display:flex;gap:15px;justify-content:center;flex-wrap:wrap;">
    <span style="background:#1f2937;padding:8px 16px;border-radius:20px;font-size:13px;border:1px solid #374151;">
        Total Ledger Records: <strong><?= count($deposits) ?></strong>
    </span>
</div>

<div style="max-width:1140px;margin:0 auto;overflow-x:auto;padding:0 10px;">

<table style="width:100%;border-collapse:collapse;background:var(--card);border:1px solid var(--border);border-radius:10px;min-width:1000px;font-size:14px;">

<thead>
<tr style="text-align:left;background:#111827;">
    <th style="padding:12px;">ID</th>
    <th style="padding:12px;">Client ID</th>
    <th style="padding:12px;">Intent Type / Order Maps</th>
    <th style="padding:12px;">Amount Due</th>
    <th style="padding:12px;">Gateway Type</th>
    <th style="padding:12px;">Submitted Payload</th>
    <th style="padding:12px;">Proof File</th>
    <th style="padding:12px;">Status</th>
    <th style="padding:12px;text-align:right;">Actions</th>
</tr>
</thead>

<tbody>

<?php if (empty($deposits)): ?>
<tr>
    <td colspan="9" style="padding:2rem;text-align:center;color:#888;">No deposit transactions found in database logs.</td>
</tr>
<?php endif; ?>

<?php foreach ($deposits as $deposit): ?>
<tr style="border-top:1px solid var(--border); vertical-align: middle;">

    <td style="padding:12px;font-family:monospace;font-weight:bold;">
        #DEP-<?= $deposit['deposit_id'] ?>
    </td>

    <td style="padding:12px;">
        <span style="display:block;font-weight:600;">UID: <?= htmlspecialchars($deposit['user_id'] ?? 'N/A') ?></span>
        <small style="color:#aaa;font-size:11px;text-transform:uppercase;"><?= htmlspecialchars($deposit['country'] ?? 'Unknown Reg') ?></small>
    </td>

    <td style="padding:12px;">
        <?php 
            $clean_order_ids = trim($deposit['order_ids'] ?? '');
            $is_order_payment = (!empty($clean_order_ids) && $clean_order_ids !== '0');
            
            if ($is_order_payment): 
        ?>
            <div style="margin-bottom: 4px;">
                <span style="background:#0284c7; color:#fff; font-size:10px; padding:2px 6px; border-radius:4px; font-weight:bold; text-transform:uppercase; letter-spacing:0.3px;">Order Payment</span>
            </div>
            <span class="order-map-badge" 
                  data-orders="<?= htmlspecialchars($clean_order_ids) ?>" 
                  data-user="<?= (int)$deposit['user_id'] ?>"
                  style="display:inline-block;padding:4px 8px;background:#1e293b;color:#38bdf8;border:1px solid #0284c7;border-radius:4px;font-family:monospace;cursor:pointer;font-weight:bold;font-size:12px;max-width:120px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;"
                  title="Click to view associated Ticket details">
                IDs: <?= htmlspecialchars($clean_order_ids) ?>
            </span>
        <?php else: ?>
            <div>
                <span style="background:#059669; color:#fff; font-size:10px; padding:3px 6px; border-radius:4px; font-weight:bold; text-transform:uppercase; letter-spacing:0.3px;">Fund Wallet Request</span>
            </div>
            <small style="color:#64748b; font-family:monospace; display:block; margin-top:2px;">Direct Balance Top-up</small>
        <?php endif; ?>
    </td>

    <td style="padding:12px;font-weight:bold;color:#34d399;">
        <?= htmlspecialchars($deposit['currency']) ?> <?= number_format($deposit['amount'], 2) ?>
    </td>

    <td style="padding:12px;">
        <div style="display:flex;align-items:center;gap:8px;">
            <?php if (!empty($deposit['method_logo'])): ?>
                <img src="../uploads/payment-methods/<?= htmlspecialchars($deposit['method_logo']) ?>" 
                     style="width:28px;height:28px;object-fit:contain;background:#fff;padding:2px;border-radius:4px;">
            <?php endif; ?>
            <span style="font-size:12px;text-transform:uppercase;background:#374151;padding:2px 6px;border-radius:4px;font-weight:bold;">
                <?= str_replace('_', ' ', $deposit['payment_type']) ?>
            </span>
        </div>
    </td>

    <td style="padding:12px;font-size:12px;max-width:220px;word-break:break-all;">
        <?php 
            $payload = json_decode($deposit['submitted_details'], true);
            if(is_array($payload)){
                foreach($payload as $key => $val){
                    if(!empty($val)){
                        echo "<strong>".htmlspecialchars(str_replace('_',' ',$key)).":</strong> ".htmlspecialchars($val)."<br>";
                    }
                }
            } else {
                echo '<span style="color:#666;">Raw: '.htmlspecialchars($deposit['submitted_details']).'</span>';
            }
        ?>
    </td>

    <td style="padding:12px;">
        <?php if (!empty($deposit['proof_file'])): ?>
            <a href="../<?= htmlspecialchars($deposit['proof_file']) ?>" target="_blank" 
               style="background:#1f2937;color:#60a5fa;border:1px solid #3b82f6;padding:4px 8px;border-radius:6px;text-decoration:none;font-size:11px;font-weight:bold;display:inline-flex;align-items:center;gap:3px;">
                <i class="fas fa-file-invoice"></i> View Proof
            </a>
        <?php else: ?>
            <span style="color:#f85149;font-size:12px;">Missing Document</span>
        <?php endif; ?>
    </td>

    <td style="padding:12px;">
        <?php 
            $status = $deposit['status'];
            $bg = '#1f2937'; $co = '#9ca3af';
            if($status === 'approved') { $bg = '#14532d'; $co = '#4ade80'; }
            if($status === 'declined') { $bg = '#7f1d1d'; $co = '#f87171'; }
            if($status === 'pending')  { $bg = '#7c2d12'; $co = '#fb923c'; }
        ?>
        <span style="background:<?= $bg ?>;color:<?= $co ?>;padding:4px 8px;border-radius:6px;font-weight:bold;text-transform:uppercase;font-size:11px;letter-spacing:0.5px;">
            <?= $status ?>
        </span>
    </td>

    <td style="padding:12px;white-space:nowrap;text-align:right;">

        <?php if($status === 'pending'): ?>
            <form method="POST" style="display:inline-block;">
                <input type="hidden" name="action" value="update_status">
                <input type="hidden" name="status" value="approved">
                <input type="hidden" name="id" value="<?= $deposit['deposit_id'] ?>">
                <button class="btn green" style="padding:5px 8px;font-size:12px;font-weight:bold;cursor:pointer;">
                    Approve
                </button>
            </form>

            <form method="POST" style="display:inline-block;margin-left:3px;">
                <input type="hidden" name="action" value="update_status">
                <input type="hidden" name="status" value="declined">
                <input type="hidden" name="id" value="<?= $deposit['deposit_id'] ?>">
                <button class="btn red" style="padding:5px 8px;font-size:12px;font-weight:bold;background:#b91c1c;cursor:pointer;">
                    Decline
                </button>
            </form>
        <?php else: ?>
            <form method="POST" style="display:inline-block;">
                <input type="hidden" name="action" value="update_status">
                <input type="hidden" name="status" value="pending">
                <input type="hidden" name="id" value="<?= $deposit['deposit_id'] ?>">
                <button class="btn" style="padding:4px 8px;font-size:11px;background:#4b5563;color:#e5e7eb;cursor:pointer;">
                    Reset to Pending
                </button>
            </form>
        <?php endif; ?>

        <form method="POST"
              onsubmit="return confirm('CRITICAL WARN: Are you sure you want to permanently purge this financial tracking ledger record? This step cannot be reversed.');"
              style="display:inline-block;margin-left:6px;">

            <input type="hidden" name="action" value="delete">
            <input type="hidden" name="id" value="<?= $deposit['deposit_id'] ?>">

            <button class="btn red" style="padding:5px 8px;font-size:12px;background:#310000;border:1px solid #f85149;color:#f85149;cursor:pointer;">
                <i class="fas fa-trash-alt"></i>
            </button>

        </form>

    </td>

</tr>
<?php endforeach; ?>

</tbody>
</table>
</div>

<div id="orderMapModal" style="display:none; position:fixed; z-index:9999; left:0; top:0; width:100%; height:100%; overflow:auto; background-color:rgba(0,0,0,0.6); backdrop-filter:blur(4px); align-items:center; justify-content:center;">
    <div style="background:#1e293b; color:#f8fafc; margin:auto; padding:24px; border:1px solid #475569; width:90%; max-width:650px; border-radius:12px; box-shadow: 0 20px 25px -5px rgb(0 0 0 / 0.5); position:relative; font-family:sans-serif;">
        <span id="closeModalBtn" style="color:#94a3b8; position:absolute; top:15px; right:20px; font-size:28px; font-weight:bold; cursor:pointer;">&times;</span>
        
        <h2 style="margin-top:0; border-bottom:1px solid #334155; padding-bottom:12px; color:#38bdf8; font-size:20px;">Order Mapping Details</h2>
        
        <div id="modalContentTarget" style="max-height:70vh; overflow-y:auto; padding-right:5px;">
        </div>
    </div>
</div>

</main>

<script>
document.addEventListener('DOMContentLoaded', function() {
    const modal = document.getElementById('orderMapModal');
    const closeBtn = document.getElementById('closeModalBtn');
    const contentTarget = document.getElementById('modalContentTarget');

    // Attach listener to order map badges
    document.querySelectorAll('.order-map-badge').forEach(badge => {
        badge.addEventListener('click', function() {
            const orderIds = this.getAttribute('data-orders');
            const userId = this.getAttribute('data-user');
            
            contentTarget.innerHTML = '<div style="text-align:center; padding:20px; color:#94a3b8;">Loading mapping matrix details...</div>';
            modal.style.display = 'flex';

            // Fire secure asynchronous payload extraction request
            fetch(`?action=get_order_details&order_ids=${encodeURIComponent(orderIds)}&user_id=${userId}`)
                .then(response => {
                    if (!response.ok) {
                        throw new Error('Network response was not ok');
                    }
                    return response.json();
                })
                .then(data => {
                    if (!data.success) {
                        contentTarget.innerHTML = `<div style="color:#ef4444; padding:10px;">Error: ${data.error}</div>`;
                        return;
                    }

                    // 1. User Details Section (Rendered at the Top)
                    let html = `
                        <div style="background:#0f172a; padding:16px; border-radius:8px; margin-bottom:20px; border-left:4px solid #38bdf8;">
                            <h3 style="margin:0 0 8px 0; color:#38bdf8; font-size:15px; text-transform:uppercase; letter-spacing:0.5px;">User Details</h3>
                            <p style="margin:4px 0; font-size:14px;"><strong>Full Name:</strong> ${escapeHtml(data.user.full_name)}</p>
                            <p style="margin:4px 0; font-size:14px;"><strong>Email:</strong> ${escapeHtml(data.user.email)}</p>
                            <p style="margin:4px 0; font-size:14px;"><strong>Country:</strong> ${escapeHtml(data.user.country)}</p>
                        </div>
                        <h3 style="margin:20px 0 10px 0; color:#cbd5e1; font-size:16px; font-weight:600;">Purchased Item Details</h3>
                    `;

                    // 2. Structural Line Items Loop (Artist, Concert & Ticket details displayed below)
                    if (data.items.length === 0) {
                        html += '<p style="color:#94a3b8; text-align:center;">No valid ticket records matched to these criteria.</p>';
                    } else {
                        data.items.forEach((item, index) => {
                            const artistImgHtml = item.artist_image 
                                ? `<img src="../uploads/artists/${escapeHtml(item.artist_image)}" style="width:50px; height:50px; object-fit:cover; border-radius:50%; border:2px solid #475569;" alt="Artist">`
                                : `<div style="width:50px; height:50px; background:#334155; border-radius:50%; display:flex; align-items:center; justify-content:center; font-size:10px; color:#94a3b8;">No Pic</div>`;

                            html += `
                                <div style="background:#1e293b; border:1px solid #334155; padding:16px; border-radius:8px; margin-bottom:15px; position:relative;">
                                    <span style="position:absolute; top:12px; right:15px; background:#334155; color:#94a3b8; font-size:11px; padding:2px 6px; border-radius:4px; font-weight:bold;">Item #${index + 1} (Order ID: ${item.order_id})</span>
                                    
                                    <div style="display:flex; align-items:center; gap:12px; margin-bottom:14px; border-bottom:1px dashed #334155; padding-bottom:10px;">
                                        ${artistImgHtml}
                                        <div>
                                            <small style="color:#94a3b8; display:block; text-transform:uppercase; font-size:10px;">Artist</small>
                                            <strong style="color:#f1f5f9; font-size:16px;">${escapeHtml(item.artist_name || 'Unknown Artist')}</strong>
                                        </div>
                                    </div>

                                    <div style="margin-bottom:12px;">
                                        <h4 style="margin:0 0 6px 0; color:#e2e8f0; font-size:14px;">Concert Title: ${escapeHtml(item.concert_title || 'Untitled Event')}</h4>
                                        <div style="display:grid; grid-template-columns: 1fr 1fr; gap:6px; font-size:12px; color:#94a3b8;">
                                            <div><strong>Concert Date:</strong> ${escapeHtml(item.concert_date)}</div>
                                            <div><strong>Day Time:</strong> ${escapeHtml(item.day_time)}</div>
                                            <div><strong>Venue:</strong> ${escapeHtml(item.venue)}</div>
                                            <div><strong>Location:</strong> ${escapeHtml(item.location)}</div>
                                        </div>
                                    </div>

                                    <div style="background:#0f172a; padding:10px; border-radius:6px; display:flex; justify-content:between; align-items:center; flex-wrap:wrap; gap:10px;">
                                        <div style="font-size:13px;">
                                            <strong style="color:#38bdf8;">${escapeHtml(item.ticket_name)}</strong> 
                                            <span style="color:#64748b; margin:0 4px;">|</span> 
                                            <span style="color:#cbd5e1;">Section: ${escapeHtml(item.section_name)}</span> 
                                            <span style="color:#64748b; margin:0 4px;">|</span> 
                                            <span style="color:#cbd5e1;">Row: ${escapeHtml(item.row_name)}</span>
                                        </div>
                                        <div style="margin-left:auto; font-weight:bold; color:#4ade80; font-size:14px;">
                                            $${parseFloat(item.price).toFixed(2)}
                                        </div>
                                    </div>
                                </div>
                            `;
                        });
                    }

                    contentTarget.innerHTML = html;
                })
                .catch(err => {
                    contentTarget.innerHTML = `<div style="color:#ef4444; padding:10px;">Execution Exception: ${err.message}</div>`;
                });
        });
    });

    // Close Actions
    closeBtn.addEventListener('click', () => modal.style.display = 'none');
    window.addEventListener('click', (e) => {
        if (e.target === modal) modal.style.display = 'none';
    });

    // Clean String Utility helper to prevent cross-site scripting vulnerabilities
    function escapeHtml(string) {
        if(!string) return 'N/A';
        return String(string).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
    }
});
</script>

<?php require_once __DIR__ . '/inc/footer.php'; ?>
